# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-06 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=35, unique=True)),
                ('nombre', models.CharField(max_length=35)),
                ('apellido', models.CharField(max_length=35)),
                ('zona_rural', models.CharField(max_length=35)),
                ('telefono', models.CharField(max_length=35)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=35)),
                ('tipo_usuario', models.CharField(max_length=35)),
            ],
        ),
    ]
