# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-06 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MercadoagroFinal', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compra', models.CharField(max_length=35, unique=True)),
                ('valor', models.CharField(max_length=35)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MercadoagroFinal.producto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MercadoagroFinal.usuario')),
            ],
        ),
    ]
